Sidoine/Ovale

Aura.lua
Future.lua

Future.lua: Added the LastSpellSent function that returns the last successful or queued spell.  Based off LastSpellInFlight function.
Aura.lua: Modified LostAuraOnGUID function to compare to a successful cast's stop time or a queued spell's queued time.
Fixes #9 in the proper way.

Snapshot bug fix

---

Data.lua

Updated Shadow Dance spell id in stealthed_buff

---

Future.lua

nil reference check

---

Scripts.lua

underscore between death and knight

Default script selection for frost DK

---

SpellBook.lua
conditions.lua

Add support for SpellCount

---

scripts/ovale_paladin.lua
scripts/ovale_paladin_spells.lua

… 11/6/2016
Added missing avengers shield action based on missing crusaders judgement talent definition
Added multiple missing shield of the righteous actions based on missing seraphim talent definition
Updated consecration action conditions based on missing crusaders judgement talent definition
Updated multiple hammer of the righteous actions based on missing crusaders judgement talent definition
Updated blinding light auction based on missing crusaders judgement talent definition
Updated required symbols
Added missing seraphim talent definition
Added missing crusaders judgement definition

Updates and Bug Fixes to Protection Paladin script based on latest SimC (11/6/2016)

---

Frame.lua
Options.lua

Trigger the redraw of the frame when settings are different between profiles

Multispec position fix

---

BossMod.lua
conditions.lua

- fix for BigWigs
- fallback when no bossmods are installed
- Add Debug and Profiler

Improving IsBossFight

---

libs/libs.xml

pkgmeta already adapted in 1080c138659d62e7ace70732054ac9ba474d9ac7

include LibRangeCheck in libs.xml

---

Stance.lua

Doesn't exist anymore so throws lua error.

Remove Claws of Shirvallah form

---

ActionBar.lua

1. Fixed issue where a change in spellId for spells that have two different versions (and spellIDs) based on the current stance wasn't detected during a stance change. This causes issues when determining the key binding.
Cause: The registered events in ActionBar.lua happen before the spellID changes during a stance changes.
Fix: Added a timer that fires one second after a stance change to rescan the spells.
2. Fixed issue where key binding for spells that have a cooldown and are on both active slots and on inactive bonus bars were incorrect.
Cause: When a spell with a cooldown is activated, blizzard fires an ACTIONBAR_SLOT_CHANGED event for every slot the spell is present in, even if that slot is on an inactive bonus bar. Unlike the code for UpdateActionSlots which only calls …

Fixed two issues with ActionBar key bindings

---

dist/scripts/ovale_druid.lua

scripts must end on a line that does not begin with #
simplest fix is to add a new line at the end.

Fix ShmooDude scripts

---

dist/Stance.lua
src/Stance.ts

Fix stances

---

dist/SimulationCraft.lua
dist/scripts/ovale_shaman.lua
dist/scripts/ovale_shaman_spells.lua
src/SimulationCraft.ts
src/scripts/ovale_shaman.ts
src/scripts/ovale_shaman_spells.ts

disambiguty for totem_mastery

---

dist/PaperDoll.lua
dist/Totem.lua
dist/conditions.lua
dist/scripts/ovale_mage_spells.lua
src/PaperDoll.ts
src/Totem.ts
src/conditions.ts
src/scripts/ovale_mage_spells.ts

Random Fixes

---

dist/BaseState.lua
dist/BossMod.lua
dist/Frame.lua
dist/Future.lua
dist/Power.lua
dist/Requirement.lua
dist/SpellFlash.lua
dist/Stagger.lua
dist/Variables.lua
dist/conditions.lua
dist/files.xml
src/BaseState.ts
src/BossMod.ts
src/Frame.ts
src/Future.ts
src/Power.ts
src/Requirement.ts
src/SpellFlash.ts
src/Stagger.ts
src/Variables.ts
src/conditions.ts

Refactor isInCombat

---

src/tools/TimeSpan.ts
src/tools/timespan.spec.ts

fix(timespan): improve check for a time contained in a timespan

---

src/ui/Frame.ts

Break up the long and unreadable logical expression into smaller
bits and document them.

refactor(frame): clarify the conditions that force a frame update

---

src/engine/ast.ts
src/engine/runner.ts

This pullup makes a few formatting changes to log messages for more
consistency and also fixes the syntax error message from parsing a
typed function.

fix: improve and fix log messages

---

Bindings.xml

fix: use correct function call for each keybind reserved by Ovale

---

src/ioc.ts
src/scripts/ovale_paladin_spells.ts
src/states/Spells.ts
src/states/spellactivationglow.ts

Spells always usable when spellactivation is active

---

src/engine/best-action.ts
src/ioc.ts
src/states/AzeriteArmor.ts
src/states/Equipment.ts
src/states/runeforge.ts

I have additional changes to the Runeforge module to allow for using either item bonus IDs or runeforge power IDs that depend on these changes, and I'll submit those when these are merged.

refactoring of Equipment module to improve correctness

---

src/engine/guid.ts
src/tools/array.spec.ts
src/tools/array.ts

I believe this fixes a bug in the implementation used in the existing
`guid` module. I've also included a fairly good set of unit tests for
this implementation.

feat: add standalone binary search/insert/remove implementation

---

src/utils/dbc.ts

* Allow for skipping the use of a Python process to create
SpellShapeshift.csv.
* Automatically detect the latest versions of the WoW build
directories from CASC and DBC extraction processes when creating
`src/utils/importsimc/types.ts`.

feat: improvements to DBC extraction

---

src/tools/Queue.ts
src/tools/list.spec.ts
src/tools/list.ts
src/tools/queue.spec.ts

Add an O(1) method to clear a list or queue of all items.

feat: add clear() method to list and queue classes

---

src/states/covenant.ts

Add a new `getCovenant()` method to return the name of the
current covenant, and a new `isCovenant()` method to check if the
given covenant matches the current one.
Fire a new Ovale event `Ovale_CovenantChosen` after the module
has reacted to `COVENANT_CHOSEN` and can return the correct
information.

feat: add method to query the current covenant
