Sidoine/Ovale

ComboPoints.lua
This line is incorrect:
if powerToken ~= SPELL_POWER_COMBO_POINTS then return end
SPELL_POWER_COMBO_POINTS = 4, while powerToken = COMBO_POINTS so it resolves to true and the combo points aren't updated.
OvalePower has the proper value for powerToken stored in the POWER_INFO variable. I've had it reference that and now works properly
P.S. Kind of new to using GitHub (or version management in general) so sorry about all the weird commits/pull requests.
=> Combo Points fix

Aura.lua
A temporary patch for #6 until Sidoine can implement a proper fix that updates the state itself with the live aura data on a detected ability miss.
Bypasses the state data for auras when a miss is detected until the state aura once again matches the live data.
=> Ability that applies debuff misses bug fix

Aura.lua
The fix is programmed specifically for Wrecking Ball/Whirlwind.  Possible there's a better place to put this but I wasn't having much luck elsewhere.  Put it there because that's the function conditions.lua calls.
Basically, the code checks if the aura is Wrecking Ball, then checks if the last (gcd) spell cast was Whirlwind.  If it was, and the aura started before the cast of Whirlwind, then sets the ending time of the aura to the starting time of the spellcast.
=> Wrecking Ball fix

Scripts.lua
Simulationcraft no longer provides seperate 1H and 2H scripts for WW. Assumes 1H anyway.
=> no weapontype in default script for WW Monk

SimulationCraft.lua, scripts/ovale_deathknight.lua
plague_strike is no longer a baseline spell for all death knights. Using death_strike instead to determine melee range.
Closes #44
=> use death_strike instead of plague_strike

BestAction.lua, Frame.lua, Icon.lua, Power.lua, SpellBook.lua
Simulationcraft will stop evaluating the action list at the point where
a pool_resource line resolves to true.  Since Ovale evaluates the entire
action list before determining an action, the equivilent in Ovale is to
ignore the resource requirement when determining the best action.
Separates out the normal cooldown (or GCD) information from the extra
time required to pool resources for a spell.
pool_resource=1 will cause BestAction to ignore any additional time
needed for resource requirements.  This mimics Simulationcraft's
pool_resource,for_next=1 functionality.
extra_amount=# will increase the cost of an ability by that amount.  It
can be used with pool_resource=1 to mimic the
pool_resource,for_next=1,extra_amount=# functionality or on an ability
that consumes extra resources such as …
=> Separate cooldown and waiting on resources

SpellBook.lua
Which I think it's weird, because _ isn't even used in variable scope.
The goal of the GetTimeToSpell is to use the class's default power anyway.
fixes #78
=> the value of _ seems to be unpredictable

conditions.lua
The current code gets the spell list from its virtual buff id correctly. 
But when iterating the list it used the virtual ID instead of the current list element resulting in either 0 or ListSize as returnValue instead of a count
=> Fix conditions.lua BuffCount

scripts/ovale_demonhunter_spells.lua
It allows me to use the SimCraft rotation (excluding infernal strike).
I don't know how to track if=!sigil_placed
```
if target.DebuffExpires(frailty_debuff) Spell(spirit_bomb)
if target.DebuffPresent(fiery_brand_debuff) Spell(soul_carver)
if Pain() <= 80 Spell(immolation_aura)
if Pain() <= 70 Spell(felblade)
if Pain() >= 30 Spell(soul_barrier)
if Pain() >= 30 and BuffStacks(soul_fragments) == 5 Spell(soul_cleave)
if BuffExpires(demon_spikes_buff) and not target.DebuffPresent(fiery_brand_debuff) and BuffExpires(metamorphosis_veng_buff) and IncomingDamage(5) > MaxHealth() * 0.7 Spell(metamorphosis_veng)
if Pain() >= 30 and IncomingDamage(5) > MaxHealth() * 0.7 Spell(fel_devastation)
if Pain() >= 30 and IncomingDamage(5) >= MaxHealth() * 0.7 Spell(soul_cleave)
if …
```
=> Add missing DH spells

ActionBar.lua
This change allows to display keybinds set with Bartender4 for it's actionbars from 1 to 10.
Requires keybinds set via Bartender, but just entering /kd and hovering over Bartender's actionbar buttons.
=> Add support for Bartender4 AC1..AC10 keybinds

Icon.lua
Its hard to calculate the correct starting time for energy based abilities because energy is reported to us as discrete but we treat it as continuous.
This change instead updates the cooldown swipe, leaving it in the same percentage completion as before, but accelerating or decelerating it for the new end time.  This allows the cooldown swipe not to start over constantly and keeps the cooldown threshold at reasonable levels (would require a cooldown threshold of 250 ms to completely stop the swipe reset for energy based characters).
=> Cooldown Swipe

dist/conditions.lua, src/conditions.ts
TimeToDie should always return a value.  It would return `undefined` (`nil`) if the mob was estimated to die before the end of you could cast your next spell.
=> TimeToDie fix

dist/Icon.lua, dist/Spells.lua, src/Icon.ts, src/Spells.ts
The range of spells has 3 different values
1: spell in range
0: spell not in range
nil: range not applicable (no target, spell has no range fi buffs or aoe spells)
=> Hide range indicator when not needed

dist/Compile.lua, dist/Data.lua, dist/Power.lua, src/Compile.ts, src/Data.ts, src/Power.ts
ItemRequire() and SpellRequire() had a limitation where a property
was set to a particular value by associating only a single
requirement handler for that value.  For example:
SpellRequire(stealth unusable 1=stealthed,1)
SpellRequire(stealth unusable 1=combat,1)
Only the second handler "combat=1" is used because only one handler
could be associated with "unusable=1" (the second SpellRequire
effectively overwrote the first).
This commit allows for handlers for multiple requirements to be
collected into an array associated with that property's value.
Checking requirements now means checking if any of the handlers in
the array are true, effectively turning multiple ItemRequire() or
SpellRequire() commands into "OR" conditionals.
Fixes issue #530 where rogues are recommended to Stealth even …
=> Enhance ItemRequire and SpellRequire to allow "OR" conditionals.

dist/conditions.lua, src/conditions.ts
The new conditions have the following correspondences:
DamageTaken(5 magic=1)    ==> MagicDamageTaken(5)
DamageTaken(5 physical=1) ==> PhysicalDamageTaken(5)
DamageTaken() is also modified to no longer accept the "magic" and
"physical" named parameters, which are currently broken.
This allows for Ovale scripts to still check for specific types of
damage taken by using the new conditions in a simple, future-proof
way.
=> Add new conditions MagicDamageTaken() and PhysicalDamageTaken().

dist/engine/data.lua, src/engine/data.ts
The Stealthed() condition just returns the presence of any of buffs
listed in "stealthed_buff". Add spell IDs for the Shadow Dance buff
and the Sepsis buff proc to the list. Also make the same change for
"rogue_stealthed_buff" for completeness.
This addresses issue #714.
=> Add additional "stealth" buffs to spell lists.

dist/engine/data.lua, dist/scripts/ovale_rogue.lua, dist/scripts/ovale_rogue_spells.lua, dist/simulationcraft/emiter.lua, src/engine/data.ts, src/scripts/ovale_rogue.ts, src/scripts/ovale_rogue_spells.ts, src/simulationcraft/emiter.ts
SimulationCraft relaxed the usage of "apply_poison" in rogue profiles to not require then "lethal" modifier that specified which lethal poison to apply.  Teach `simulationcraft/emiter.ts` to emit either "deadly_poison" or "instant_poison" depending on the rogue specialization in order to match the semantics in `simc:sc_rogue.cpp`.
=> Translate "apply_poison" in SimulationCraft profiles again.

src/scripts/ovale_common.ts, src/states/covenant.ts
Enumerate all of the covenents and their corresponding IDs in a
COVENENT_ID_BY_NAME table and allow using names with the
IsCovenant() condition.
Modify the IsCovenant() condition to accept either a number or a
string for the parameter name.
This removes the need for the defintions in scripts/ovale_common
for `kyrian`, `venthyr`, `night_fae`, and `necrolord`, as these
strings can be used directly by IsCovenant().
=> Teach the Covenant class to manage its own ID <-> name mapping.

src/engine/ast.ts, src/engine/data.ts, src/ui/Frame.ts
At one point, it may have been set as a paramter to AddIcon to
ignore the cooldown of the spell being displayed, but that hasn't
been used in at least 12 years, and the usage of "nocd" somehow
changed over time without any documentation on the new semantics.
Removing it to make the remaining codepath slightly clearer.
=> Remove bitrotted and likely incorrect code regarding "nocd".

src/ui/Icon.ts
Always show the cooldown frame if the icon is displaying an action
that has a cooldown.  The frame's Show() method was not being
triggered when the icon was showing a texture again.
This fixes issue #739.
=> fix: show cooldown frame if a cooldown is active

src/states/covenant.ts
There is no need to call "tostring" after we've checked that it's
already a string. Simply use "as string" to help with type
assertion.
This commit is a small optimization, but is mostly to test that
my development environment works correctly to use nodejs
to turn TypeScript into Lua correctly.
=> Remove unnecessary use of "tostring".

package.json, src/ui/Version.ts, yarn.lock
AceTimer:ScheduleTimer() expects "PrintVersionCheck" to be a method
of "this.module", but no such method exists.
Use the correct function "this.PrintVersionCheck" and pass "this"
as a parameter to the function so that the method is called on the
correct object.
This fixes "/ovale ping" to allow checking for other users of Ovale
in the group or in the guild (if not in a group).
=> fix: register correct callback to AceTimer:ScheduleTimer()

src/engine/best-action.ts, src/ioc.ts, src/states/Power.ts, src/states/Spells.ts
These commits will cause a spell to not be suggested if their
power requirements cannot be met simply by waiting, e.g., chi,
holypower, combopoints, runicpower, etc.
This will cause most scripts to correctly fall through to other
spells which can be cast instead of suggesting a spell that is
waiting on resources.
=> Spells are usable only if they meet all of their power requirements

src/engine/ast.ts, src/engine/controls.ts, src/simulationcraft/definitions.ts, src/simulationcraft/emiter.ts, src/simulationcraft/generator.ts
This pullup should be merged without squashing. It fixes two bugs in `engine/controls.ts` and `engine/ast.ts` and also improves the translation of the SimC `desired_targets` operand in Ovale scripts (#236).
The default scripts should be regenerated after this pullup is complete.
=> Improve translation of "desired_targets" from SimulationCraft.

src/simulationcraft/emiter.ts, src/states/Totem.ts
This pullup does the following:
* Adds totem support to every class since almost all classes can summon guardians which are treated in-game as totems.
* Try to pattern-match for `EmitOperandSpecial()` before falling through to the rest of the pet operand logic. This allows for
handling of special cases sooner in the flow.
* Fix translating death knight ghouls.
* Fix translating monk pets.
This fixes issue #761.
=> Fix script translations of totem pets

src/engine/condition.ts, src/scripts/ovale_warrior.ts, src/simulationcraft/definitions.ts, src/simulationcraft/emiter.ts, src/simulationcraft/generator.ts, src/states/AzeriteArmor.ts, src/states/Equipment.ts, src/states/Stagger.ts, src/states/Stance.ts, src/states/Variables.ts, src/states/Warlock.ts, src/states/combat.ts, src/states/conditions.ts
This pullup does three things:
* Modifies `engine/condition.ts` and the state modules to stop accepting "comparator-limit" parameters, e.g., `ValueCondition(less 5)` instead of `ValueCondition() < 5`, and "yesno" parameters, e.g., `BooleanCondition(no)` instead of `not BooleanCondition()`. 
* Cleans up the usage of `TestValue()` and `Compare()`, replacing them with `ReturnValue()` and `ReturnConstant()`.
* Fixes `simulationcraft` modules to stop using "comparator-limit" parameters in the warrior script.
=> refactor: condition cleanup

src/scripts/ovale_deathknight.ts, src/scripts/ovale_hunter.ts, src/scripts/ovale_hunter_spells.ts, src/simulationcraft/emiter.ts, src/utils/importsimc/fixes.ts
This pullup fixes the spell ID for BM hunter pet Frenzy buff and
modifies `simulationcraft/emiter.ts` so that it translates the
following correctly:
* buff.dark_transformation.<property>
* buff.beast_cleave.<property>
* buff.frenzy.<property>
=> fix: check for correct buffs on pets

src/scripts/ovale_demonhunter_spells.ts
You can't infernal strike or metamorphosis (the Havoc version) when rooted
=> fix(demonhunter): leaping not possible when rooted

src/scripts/ovale_deathknight_spells.ts
Raise Dead and Summon Gargoyle are totem spells, and Sacrificial
Pact can only be cast if a ghoul is active.
=> fix(deathknight): mark totem spells and fix sacrificial_pact

src/states/Equipment.ts, src/states/Stagger.ts, src/states/Variables.ts, src/states/combat.ts, src/states/conditions.ts
Remove the documented return of a boolean value that can no longer
occur after 9059639affcdb1f754fa50be5805295683c6b5a8 which removed
the comparator-limit parameters from conditions.
=> docs(conditions): remove impossible return values from documentation

src/ui/Icon.ts
Ensure that the first argument to SetText() is non-nil and only
show the shortcut/keybind if true.
Fixes issue #780.
=> fix(icon): fix nil arguments to SetText()

src/states/conditions.ts
TimeToRunes() returns a value of the number of seconds relative to
the current time. This should be a linear equation, not a simple
constant.
=> fix(conditions): return a proper value for TimeToRunes()

src/engine/best-action.ts
The idiom that was used to set the texture was unnecessary when
the variables were all local, but is plain wrong when using
"result" fields because it would never overwrite a cached result's
texture. Simplify by using a simple if-else statement to set the
texture.
This fixes issue #749.
=> fix(best-action): always use the correct texture for actions

src/engine/runner.ts
This pullup fixes the computation of `A>?B` and `A<?B` by computing
the proper timespans and functions for the results. The value of
`A>?B` was previously computing the minimum.
It also documents each of the computations so that it's easier to
check the code matches the mathematics.
=> fix(runner): fix ComputeArithmetic() for >? and <? operators

src/engine/ast.ts, src/engine/data.ts, src/ioc.ts, src/scripts/ovale_druid.ts, src/scripts/ovale_druid_spells.ts, src/simulationcraft/definitions.ts, src/simulationcraft/emiter.ts, src/states/Aura.ts, src/states/conditions.ts
This pullup makes many fixes to the feral druid spell definitions,
adds an implementation for `TicksGainedOnRefresh()` used by the
default feral scripts, and fixes the importer to emit the correct
script code for `druid.<spell>.ticks_gained_on_refresh`.
The feral script seems usable now with some light testing against
a target dummy on a level 52 feral druid.
This fixes issue #777.
=> fix(druid): many fixes and improvements to feral script

src/states/SpellBook.ts, src/states/Spells.ts
Revert 86439eb31f273ab217bfd4decce845f88b09f7f2 and fix the
underlying problem in a different way. That commit used the WoW
IsUsableSpell() API function to determine whether a spell is known,
but that returns false if the spell is genuinely not usable due to
either cooldown or power requirements. Fix this in a better way by
teaching SpellBook.ts:IsKnownSpell() to check for a spell being
known to the player even if it's not in the spellbook by using the
WoW IsSpellKnown() API function.
While here, adjust IsUsableSpell() so that there is only a single
exit point from the function to make the profiler stats work
correctly.
=> fix: properly check for known spells in InUsableSpell()

src/scripts/ovale_deathknight_spells.ts
Apocalypse, Scourge Strike, and Festering Strike all modify the
stack count of Festering Wounds on the current target. This helps
the simulator to predict the correct next spell to cast.
=> fix(deathknight): annotate abilities that modify Festering Wound stacks

src/scripts/ovale_rogue.ts, src/simulationcraft/generator.ts
Outlaw rogues can't stun anymore with Between the Eyes, but can use
Kidney Shot instead.
=> fix(rogue): outlaw rogues stun using a different spell

src/scripts/ovale_common.ts
Add special conditions to some trinkets so they don't get proposed when not usable or inefficient to use.
=> Special trinket conditions

src/engine/best-action.ts
When a spell is annotated to be replaced by another spell using the
SpellInfo parameter 'replaced_by', keep searching along the chain
of spells for other 'replaced_by' directives until we reach the
final replacement spell.
This should fix issue #833.
=> fix: follow 'replaced_by' SpellInfo chain to the final replacement

src/states/Power.ts
When `set_<powerType>` is given in SpellInfo(), use that as the
value to which the power should be set after the spell is
successfully cast.  Ensure that the cost of the spell given by
`<powerType>` is met even if `set_<powerType>` is given.
If `max_<powerType>` is given in SpellInfo(), use that as the max
cost of the spell.  Use `getProperty()` instead of directly
accessing the value so that any spell requirements are handled at
runtime.  Note that power cost from `set_<powerType>` has
precedence over the cost from `max_<powerType>`.
Lastly, always evaluate `refund_<powerType>` to determine the
amount of power refunded after the spell is successfully cast.
With this change, a combo-point finisher spell can be defined in
two different ways:
SpellInfo(finisher combopoints=1 …
=> fix(power): fix semantics of {max,set,refund}_XXX in SpellInfo()

src/ioc.ts, src/states/runeforge.ts
Imported runeforge ids in spells.ts correspond to the equipped bonus item id for the respective legendary item.
Therefore we want to scan (and keep in memory) which legendaries we have equipped and which bonus item id is specified. We look it up with an itemlink scan.
=> Fix for legendary power

src/states/DamageTaken.ts
WoW 9.1 API no longer has SCHOOL_MASK_* as global constants.
Use the correct Enum.Damageclass.* constants instead.
=> fix: use correct bitmask constant names in OvaleDamageTaken

src/states/runeforge.ts
Instead of using legendary bonus IDs in scripts, allow using the runeforge power IDs to identify equipped runeforge powers.  The `EquippedRuneforge()` script condition checks that the given id is either a legendary bonus ID or a runeforge power ID.
A future update should probably remove the use of legendary bonus IDs. They are fragile and not necessarily computed correctly because we have to make the assumption that the first bonus ID on a piece of equipment is the legendary bonus ID, and this is not documented anywhere and will probably break in a future patch.  The runeforge power ID is always correct and we query it using the documented API.
The default scripts should be changed to use runeforge power IDs instead of the legendary bonus IDs, but that's an `importsimc` issue that I won't …
=> feat(runeforge): allow using runeforge power IDs in scripts

src/ioc.ts, src/states/Aura.ts, src/states/Cooldown.ts, src/states/Future.ts, src/states/LastSpell.ts, src/states/PaperDoll.ts, src/states/Power.ts, src/states/Runes.ts, src/states/Warlock.ts, src/states/conditions.ts
Blizzard removed almost every form of DoT snapshotting since Warlords
of Draenor. This branch removes most of the code associated with
snapshotting from the codebase and does minor cleanups of the modules
touched by the changes.
=> refactor: remove snapshots

src/states/PaperDoll.ts
This fixes an issue with the game client hanging when changing
specializations and a new equipment set is auto-equipped.
=> fix: game client hanging when equipping different equipment set

src/engine/guid.ts, src/states/BossMod.ts, src/states/Future.ts, src/states/conditions.ts
This avoids needing to do the name-realm dance to get the correct
name of the unit.
=> fix: change usage of UnitName() to GetUnitName()

src/tools/cache.spec.ts, src/tools/cache.ts, src/tools/list.spec.ts, src/tools/list.ts
Add doubly-linked list implemented as a circular list. The API of
the `List` class is almost identical to the `Deque` API.
A `List` uses more memory than a `Queue`, but a `List` takes O(1)
time to do insertions and removals anywhere in the list, whereas a
`Queue` only takes O(1) time to do insertions and removals at the
front and back of the queue, and O(n) everywhere else.
Also add a testsuite for the `List` class.
=> feat: add doubly-linked list implementation

src/engine/combat-log-event.ts, src/ioc.ts, src/states/Aura.ts, src/states/DamageTaken.ts, src/states/DemonHunterDemonic.ts, src/states/DemonHunterSigils.ts, src/states/DemonHunterSoulFragments.ts, src/states/Enemies.ts, src/states/Future.ts, src/states/Health.ts, src/states/SpellDamage.ts, src/states/Stagger.ts, src/states/Warlock.ts
Move all `COMBAT_LOG_EVENT`-related code to a new module and teach
all modules to use it instead.  The benefits of using the
`CombatLogEvent` module are mainly for type-safety.
=> refactor: move COMBAT_LOG_EVENT-related code to a new module

src/tools/Queue.ts, src/tools/list.ts
This fixes a codegen issue where `tstolua` could not guess that the
return type of `queue.frontToBackIterator()` was a class type, and
the same issue for `list`.
=> fix: be explicit about method return type as a hint to tstolua

src/engine/guid.ts
Keep a cache of the last 100 unused GUIDs that no longer have unit
IDs associated with them. Once they are evicted from the cache,
remove all other information tracked by the `guid` module for those
GUIDs.  This prevents the number of GUID-to-name mappings from
growing without bound, and frees up some memory for garbage
collection.
=> feat: cache GUIDs without any unit IDs mappings for later removal

src/ioc.ts, src/states/Stagger.ts
* OvaleStaggerClass is not a StateModule.
* Remove unused variables and imports.
* Maintain a queue of recent Stagger ticks.
* Only track Stagger ticks for Brewmaster monks.
* Empty queue when Stagger pool is empty, not when combat ends.
=> fix: cleanup Stagger module

src/ioc.ts, src/states/DemonHunterDemonic.ts, src/states/DemonHunterSigils.ts, src/states/DemonHunterSoulFragments.ts
The demon hunter modules were not handling state correctly. In a
state module, the module registers for events to track what is
currently happening "live" in-game, and updates the current state
of the game based on those events. A state module also implements
the `StateModule` interface and does two things:
1. Update the simulator state from the current state each time
`resetState()` is called.
2. Modify the simulator state after various `applySpell*()`
functions are called.
Lastly, script conditions that query information from state modules
should query that information from the simulator state, not the
current state.
Make these changes to the three demon hunter modules that track the
Demonic talent, sigils, and Soul Fragments, respectively.
=> fix: rewrite demon hunter modules to correctly handle state

src/ioc.ts
This was missing from cc3923d60de8eb556893638ddfcb77bfdf4e1bdf.
=> fix: register state for demonic and soul fragment DH modules
